trigger:
- main

pool:
  name: PipelineAgent
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  displayName: 'Maven clean and verify'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify -Dcucumber.filter.tags="@ECOM_LoginTC_207 or @ECOM_LoginTC_231'

