trigger:
- main

pool:
  name: PipelineAgent
  vmImage: ubuntu-latest

variables:
  mavenPOMFile: 'pom.xml'
  options: '-Dcucumber.filter.tags="@ECOM_LoginTC_207 or @ECOM_LoginTC_231'

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'
    goals: 'clean test'
    options: '$(Parameters.options)'
    testResultsFiles: '**/surefire-reports/TEST-*.html'
