trigger:
- main

pool:
  name: PipelineAgent
  vmImage: ubuntu-latest

variables:
  defaultTag: "@AIEngine"
  customTags: "[@ECOM_LoginTC_207, @ECOM_LoginTC_231]"

steps:
- powershell: |
    $tags = "$(tags)"
    if ($tags -ne "" -and $tags -ne "[]") {
      if ($tags -like "*[*]") {
        $tagsList = $tags.Replace(" ", "").Trim("[]")
        $options = "-Dcucumber.filter.tags=""$tagsList"""
      } else {
        $options = "-Dcucumber.filter.tags=""$tags"""
      }
    } else {
      $options = "-Dcucumber.filter.tags=""$(defaultTag)"""
    }
    Write-Host "Options: $options"
    Write-Output $options | Out-File -FilePath "$(Build.SourcesDirectory)\maven-options.txt"
  displayName: 'Set Maven options'

- task: Maven@4
  displayName: 'Maven clean and verify'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify'
    options: $(Build.SourcesDirectory)\maven-options.txt
   
- task: CopyFiles@2
  displayName: 'Copy Cucumber reports'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/ExecutionReports'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/CucumberReports'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Cucumber reports as artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/CucumberReports'
    ArtifactName: 'CucumberReports'
