trigger:
- main

pool:
  name: PipelineAgent
  vmImage: ubuntu-latest

variables:
  defaultTag: "@AIEngine"
  customTags: "[@ECOM_LoginTC_207,@ECOM_LoginTC_231]"

steps:
- powershell: |
    $customTags = "$(customTags)"  # Get the customTags variable
    $tagsArray = $customTags -split ',' | ForEach-Object { $_.Trim('[', ']') }  # Split and trim the tags
    
    if ($tagsArray -eq $null -or $tagsArray.Count -eq 0) {
        $options = ""  # Empty options if customTags list is empty
    } else {
        $tagsString = $tagsArray -join " or "  # Join the tags with " or "
        $options = "$tagsString"
    }

    Write-Host "Options: $options"
    Write-Output $options  # Output options directly as a variable
  displayName: 'Set Maven options'
  name: mavenOptions  # Store the output as a variable named mavenOptions

- task: Maven@4
  displayName: 'Maven clean and verify'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify'
  env:
    MAVEN_OPTS: '-Dcucumber.filter.tags="$(mavenOptions)"'  # Pass mavenOptions as environment variable
 
- task: CopyFiles@2
  displayName: 'Copy Cucumber reports'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/ExecutionReports'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/CucumberReports'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Cucumber reports as artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/CucumberReports'
    ArtifactName: 'CucumberReports'
