trigger:
- main

# Specify the agent pool and agent
pool:
  name: 'PipelineAgent'
  demands:
    - agent.name -equals PipelineAgent

# Environment variables for Maven settings
variables:
  MAVEN_OPTS: "-Xmx1024m"
  TAGS: "@ECOM_LoginTC_207 or @ECOM_LoginTC_231"

steps:

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    options: '-Dcucumber.filter.tags="$(TAGS)"'
  displayName: 'Run Selenium Tests with Maven'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Cucumber Test Results'
    mergeTestResults: true
  displayName: 'Publish Test Results'
